spring:
  thymeleaf:
    mode: HTML
  mail:
    host: smtp.126.com #发送邮件服务器
    username: InvisibleMouse@126.com #发送邮件的邮箱地址
    password:  invisible126 #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 994 #端口号465或587
    from: InvisibleMouse@126.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  profiles:
    active: pro

