spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hublog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8    #To use mysql jar 8.0, must modify time
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  mail:
#    host: smtp.qq.com
#    username: 1519846021@qq.com
#    password: vgjzewioswaoffcj
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    default-encoding: utf-8
logging:
  level:
    root: info
    com.mouse: debug
  file: log/blog-dev.log
