spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://148.70.187.228:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8    #To use mysql jar 8.0, must modify time
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
logging:
  level:
    root: warn
    com.mouse: warn