spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hublog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8    #To use mysql jar 8.0, must modify time
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.126.com #发送邮件服务器
    username: InvisibleMouse@126.com #发送邮件的邮箱地址
    password:  invisible126 #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 994 #端口号465或587
    from: InvisibleMouse@126.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
#  mail:
#    host: smtp.qq.com
#    username: 1519846021@qq.com
#    password: vgjzewioswaoffcj
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    default-encoding: utf-8
logging:
  level:
    root: info
    com.mouse: debug
  file: log/blog-dev.log
